---
- name: Rodando container docker do mysql
  docker_container:
    name: "banco"
    image: mysql:5.6
    env: 
      MYSQL_ROOT_PASSWORD: senha
    volumes:
      - /database:/var/lib/mysql
    state: started
  become: true
  
- name: Rodando container docker wordpress
  docker_container:
    name: "blog"
    image: "wordpress"
    links: "banco:mysql"
    ports: 80:80
    state: started
  become: true

- name: Cria o arquivo de inicializacao a partir do template
  template:
    src: ../templates/containers.j2
    dest: /etc/systemd/system/containers.service
    owner: root
    group: root
    mode: 644

- name: Configura os containers na inicializacao do sistema
  systemd:
    name: containers
    state: started
    enabled: yes
  become: true
